export const SEO = {
  title: "Blink Eye | Best Eye Care & Break Timer for Mac, Windows, Linux",
  description:
    "A minimalist eye care reminder app to reduce eye strain, featuring customizable timers, full-screen popups, audio mute.",
  keywords: [
    "prevent rsi app",
    "prevent cvs app",
    "rsi app",
    "cvs app",
    "best eye care app 2024",
    "screen break reminder app",
    "free eye health app download",
    "open source eye protection software",
    "screen timer for eye care",
    "work break reminder tool",
    "eye comfort app for Mac",
    "vision care software for laptops",
    "top eye relaxation app",
    "PC screen time control",
    "computer eye care utility",
    "digital eye strain prevention",
    "windows break time scheduler",
    "best apps for eye strain relief",
    "cross-platform eye care app",
    "top open source break reminder",
    "blink timer for computer health",
    "best eye care app for Windows and Linux",
    "free eye health app for Windows",
    "open source eye protection software for Linux",
    "screen break reminder app for Windows",
    "eye comfort app for Linux",
    "top eye relaxation app for Windows",
    "digital eye strain prevention for Windows",
    "computer eye care utility for Linux",
    "work break reminder tool for Windows",
    "screen time control for Linux",
    "cross-platform eye care app",
    "best apps for eye strain relief on Windows and Linux",
    "PC screen timer for eye care",
    "vision care software for Windows",
    "eye care reminder app for Linux",
    "blink eye",
    "blink eye for windows",
    "Noman Dhoni Made App",
    "eye care app for windows",
    "20 20 20 rule app for windows",
    "eye care",
    "eye strain relief app",
    "eye health app",
    "blink eye download",
    "blink eye review",
    "20 20 20 rule app",
    "eye care reminder app",
    "eye care software",
    "eye care tips",
    "eye exercises app",
    "eye protection app",
    "eye care app for pc",
    "eye care app for laptop",
    "eye care app for desktop",
    "eye care app for windows 10",
    "eye care app for windows 11",
    "blink eye download",
    "blink eye review",
    "eye care app for windows",
    "20 20 20 rule app for windows",
  ],
  thumb: "https://utfs.io/f/93hqarYp4cDdRfdEFOs3IvZkCG1g7rYl8WhFVBbNozK265eA",
  url: "https://blinkeye.vercel.app",
  twitter: "@blinkeyeapp",
};
