export const SEO = {
  title: "Blink Eye - Best Free Eye Care & Break Timer for Mac, Windows, Linux",
  description:
    "A minimalist eye care reminder app to reduce eye strain, featuring customizable timers, full-screen popups, audio mute.",
  keywords: [
    "best eye care app 2024",
    "screen break reminder app",
    "free eye health app download",
    "open source eye protection software",
    "screen timer for eye care",
    "work break reminder tool",
    "eye comfort app for Mac",
    "vision care software for laptops",
    "top eye relaxation app",
    "PC screen time control",
    "computer eye care utility",
    "digital eye strain prevention",
    "windows break time scheduler",
    "best apps for eye strain relief",
    "cross-platform eye care app",
    "top open source break reminder",
    "blink timer for computer health",
    "best eye care app for Windows and Linux",
    "free eye health app for Windows",
    "open source eye protection software for Linux",
    "screen break reminder app for Windows",
    "eye comfort app for Linux",
    "top eye relaxation app for Windows",
    "digital eye strain prevention for Windows",
    "computer eye care utility for Linux",
    "work break reminder tool for Windows",
    "screen time control for Linux",
    "cross-platform eye care app",
    "best apps for eye strain relief on Windows and Linux",
    "PC screen timer for eye care",
    "vision care software for Windows",
    "eye care reminder app for Linux",
    "blink eye",
    "blink eye for windows",
    "Noman Dhoni",
    "Noman Dhoni Made App",
    "nomandhoni",
    "eye care app for windows",
    "20 20 20 rule app for windows",
    "eye care",
    "eye strain relief app",
    "eye health app",
    "blink eye download",
    "blink eye review",
    "20 20 20 rule app",
    "eye care reminder app",
    "eye care software",
    "eye care tips",
    "eye exercises app",
    "eye protection app",
    "blink eye alternative",
    "eye care app for android",
    "eye care app for ios",
    "eye care app for pc",
    "eye care app for laptop",
    "eye care app for desktop",
    "eye care app for chrome",
    "eye care app for firefox",
    "eye care app for safari",
    "eye care app for edge",
    "eye care app for windows 10",
    "eye care app for windows 11",
    "eye care app for windows 8",
    "eye care app for windows 7",
    "eye care app for windows xp",
    "eye care app for windows vista",
    "eye care app for windows 2000",
    "eye care app for windows 98",
    "eye care app for windows 95",
    "eye care app for windows 3.1",
    "eye care app for windows nt",
    "eye care app for windows me",
    "eye care app for windows ce",
    "blink eye download",
    "blink eye review",
    "eye care app for windows",
    "20 20 20 rule app for windows",
    "eye care reminder app",
    "eye care software",
    "eye care tips",
    "eye exercises app",
    "eye protection app",
    "eye care",
    "eye health app",
    "20 20 20 rule app",
  ],
  thumb:
    "https://repository-images.githubusercontent.com/749625079/db502010-82d3-4004-8e01-283d20915ee0",
  url: "https://blinkeye.vercel.app",
  twitter: "@blinkeyeapp",
};
