export const SEO = {
  title: "Blink Eye",
  description:
    "A minimalist eye care reminder app to reduce eye strain, featuring customizable timers, full-screen popups, audio mute.",
  keywords: [
    "blink eye",
    "blink eye for windows",
    "eye care app for windows",
    "20 20 20 rule app for windows",
    "eye care",
    "eye strain relief app",
    "eye health app",
    "blink eye download",
    "blink eye review",
    "20 20 20 rule app",
    "eye care reminder app",
    "eye care software",
    "eye care tips",
    "eye exercises app",
    "eye protection app",
    "blink eye alternative",
    "eye care app for android",
    "eye care app for ios",
    "eye care app for pc",
    "eye care app for laptop",
    "eye care app for desktop",
    "eye care app for chrome",
    "eye care app for firefox",
    "eye care app for safari",
    "eye care app for edge",
    "eye care app for windows 10",
    "eye care app for windows 11",
    "eye care app for windows 8",
    "eye care app for windows 7",
    "eye care app for windows xp",
    "eye care app for windows vista",
    "eye care app for windows 2000",
    "eye care app for windows 98",
    "eye care app for windows 95",
    "eye care app for windows 3.1",
    "eye care app for windows nt",
    "eye care app for windows me",
    "eye care app for windows ce",
    "blink eye download",
    "blink eye review",
    "eye care app for windows",
    "20 20 20 rule app for windows",
    "eye care reminder app",
    "eye care software",
    "eye care tips",
    "eye exercises app",
    "eye protection app",
    "eye care",
    "eye health app",
    "20 20 20 rule app",
  ],
  thumb: "/images/thumb.png",
  url: "http://blinkeye.verel.app",
  twitter: "@nomandhoni",
};
